baseURL: "https://alexandre-bismuth.github.io" 
title: Alexandre Bismuth
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Papers
        #   url: papers/
        #  weight: 5
        - name: Resume
          url: resume/
          weight: 2
        - name: Research
          url: research_projects/
          weight: 3
        - name: Course Projects
          url: course_projects/
          weight: 4
        - name: Side Projects
          url: side_projects/
          weight: 5
        - name: Blog
          url: blog/
          weight: 6


params:
    description: "This website hosts Alexandre Bismuth's curriculum vitae, contact information, projects, and blog."
    author: Alexandre Bismuth
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["resume","research_projects","course_projects","blog","side_projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alexandre Bismuth
          subtitle: "I am an incoming Data Science student at Harvard University and a student researcher for the British Open-Ended Learning & Discovery Lab. Previously, I obtained a BSc in Mathematics and Computer Science from École Polytechnique and (soon) an MSc in Advanced Computer Science from the University of Oxford."
          imageUrl: "prof_pic.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Resume
              url: resume/
            # - name: Papers
            #   url: papers/
            - name: Research
              url: research_projects/
            - name: Course Projects
              url: course_projects/
            - name: Side Projects
              url: side_projects/
            - name: Blog
              url: blog/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:abismuth@g.harvard.edu
        - name: Calendly
          url: https://calendly.com/alexbismuth10/quick-meet
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/alexandre-bismuth
        # - name: Substack
        #   url: https://user.substack.com
        - name: Twitter
          url: https://x.com/alex_bsmth
        - name: YouTube
          url: https://www.youtube.com/@KoVer10

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alexandre Bismuth"
      icon: "prof_pic.png"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2